"""Generate checkbox metadata; preserve existing data-task-id values when editing."""
from pathlib import Path
import json
import re
import markdown
from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parents[1]
legacy = json.loads((ROOT / 'scripts/progress-legacy.json').read_text(encoding='utf-8'))
manifest = {}
identities = set()
for number in range(10):
    page = f'stage-{number:02}'
    content = (ROOT / f'docs/ai-agent/{page}.md').read_text(encoding='utf-8')
    soup = BeautifulSoup(markdown.markdown(content, extensions=['pymdownx.tasklist', 'pymdownx.superfences']), 'html.parser')
    entries = []
    for item in soup.select('li.task-list-item'):
        marker = item.select_one('[data-task-id]')
        if not marker:
            raise ValueError(f'Missing stable task ID in {page}: {item.get_text()}')
        identity = marker['data-task-id']
        if identity in identities:
            raise ValueError(f'Duplicate task ID: {identity}')
        identities.add(identity)
        text = re.sub(r'\s+', ' ', item.get_text()).strip()
        heading = item.find_previous('h2')
        optional = number == 7 or (number == 8 and heading and '步骤 4' in heading.get_text())
        entries.append({'id': identity, 'default': item.select_one('input').has_attr('checked'),
                        'optional': bool(optional), 'legacy': legacy.get(text, [])})
    manifest[page] = entries
output = '// Generated by scripts/build_progress.py; do not edit by hand.\nwindow.ROADMAP_TASKS = ' + json.dumps(manifest, ensure_ascii=False, indent=2) + ';\n'
(ROOT / 'docs/assets/javascripts/progress-data.js').write_text(output, encoding='utf-8')
print(f'Generated {len(identities)} stable task IDs; {sum(not t["optional"] for ts in manifest.values() for t in ts)} core tasks.')
